EXPR_NAME: swin
SEED: 42
PROJ_ROOT: "/data/private/train"
DATA_PATH: "/data/project/rw/movienet"
LOAD_FROM: "" # ex) swin
PRETRAINED_LOAD_FROM: swin # ex) swin
#LOGGING:
#  LOG_FREQ: 100
#  CKPT_FREQ: -1  # -1: save last epoch model only.
TRAINER:
  accelerator: ddp
  precision: 32
  max_epochs: 20
  terminate_on_nan: True
  flush_logs_every_n_steps: 100
  num_sanity_val_steps: 0
DATASET: movienet
USE_RAW_SHOT: False  # False to use pre-extracted shot representation
TEST:
  VAL_FREQ: 1
  TRANSFORM:
    - name: VideoResizedCenterCrop
      image_size: 256
      crop_size: 224
    - name: VideoToTensor
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
TRAIN:
  USE_SINGLE_KEYFRAME: True  # only for train_mode
  NUM_KEYFRAME: 3
  TRANSFORM:
    - name: VideoRandomResizedCrop
      size: 224
      bottom_area: 0.14
    - name: VideoRandomHFlip
    - name: VideoRandomColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.05
      p: 0.8
      consistent: True
    - name: VideoRandomGaussianBlur
      radius_min: 0.1
      radius_max: 2.0
      p: 0.5
    - name: VideoToTensor
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  BATCH_SIZE: 1024
  COLLATE_FN: default_collator
  NUM_WORKERS: 8
  PIN_MEMORY: True
  OPTIMIZER:
    name: adam
    weight_decay: 0
    regularize_bn: False
    regularize_bias: False
    lr:
      base_lr: 0.0000025
      base_lr_batch_size: 256
      auto_scale: True
    scheduler:
      name: cosine_annealing
      warmup: 0.0
MODEL:
  use_sync_bn: True  # for sync_batchnorm in PYL
  neighbor_size: 8
  shot_encoder:
    enabled: False
    name: resnet
    resnet:
      input_shape: [3, 224, 224]
      depth: 50
      use_imagenet_pretrained: False  # use 3-channel 2D ResNet pretrained on ImageNet.
      params:
        zero_init_residual: True
        in_channel_dim: 3
  contextual_relation_network:  # CRN
    enabled: True
    name: swin
    swin:
      input_dim: 2048
      d_model: 768
      num_layers: [2, 2]
      num_heads: [3, 6]
      window_size: [8, 4]
      hidden_dropout_prob: 0.1
    pool:
      d_model: 768
      dropout_ratio: 0.1
LOSS:
DISTRIBUTED:
  NUM_NODES: 1
  NUM_PROC_PER_NODE: 1 # num of gpus
